version: "3.9"

services:
  shell:
    build:
      context: .
      target: dependencies
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    ports:
      - 9229:9229
      - 9230:9230
  server:
    build:
      context: .
      target: artifact
    command: node . server
  client:
    build:
      context: .
      target: artifact
    command: node . client
    environment:
      DELAY:
      SERVER_ADDRESS: dns:///server:50051

volumes:
  node_modules:
