version: "3.9"

services:
  shell:
    build: .
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    ports:
      - 9229:9229
      - 9230:9230
  server:
    build: .
    command: node . server
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    ports:
      - 9229:9229
  client:
    build: .
    command: node . client
    environment:
      SERVER_ADDRESS: dns:///server:50051
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    ports:
      - 9230:9230

volumes:
  node_modules:
